### PR TITLE
Php7 upgrade

### PR DESCRIPTION
**Pull request by morrislaptop**
#4 , well tickle me sideways, I did some more reading and managed to upgrade with all tests passing. I don't think this would easily go into an abstraction library so I'll just leave this here and you can do what you like :)

### CODE REVIEW

**Comment by thatdatabaseguy** [comment]
Right on! When I get a minute I'll either #ifdef it out or try it with pecl-compat.

**Comment by tuupola** [comment]
Any news on this?

**Comment by bedokuroff** [comment]
Hi guys, what's the status of this? Would be really helpful to have php7 support, or at least some news regarding its possible availability. Or maybe some things that need to be changed? I can help if any of the maintainers at least show me the direction :-)

**Comment by thatdatabaseguy** [comment]
@morrislaptop  @tuupola @bedokuroff this is merged into master now, though in a different PR (#10) as I wanted to retain compatibility with PHP5 as well.

**Comment by tuupola** [comment]
Awesome. Thanks!

**Pull request closed without merging**
